name: Verify installation (automatic)
on:
  pull_request:
    types: [opened, reopened, edited, synchronize, review_requested]
    paths:
      - 'external/*.conf'
  workflow_dispatch:

jobs:

  Cancel:
    name: "Cancel currently active"
    if: ${{ github.repository_owner == 'Armbian' }}
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        if: ${{ github.event.schedule == '' }}
        with:
          all_but_latest: true
          access_token: ${{ secrets.GITHUB_TOKEN }}

  external:
    name: "Download external"
    needs: Cancel

    if: ${{ github.repository_owner == 'Armbian' }}
    uses: armbian/scripts/.github/workflows/download-and-test-external.yml@main
    with:
      ACCESS_NAME: armbian
      BUILD_RUNNER: ${{ inputs.BUILD_RUNNER }} || "ubuntu-latest"
      REFERENCE: ${{ github.event.pull_request.head.sha }}
    secrets:
      GPG_KEY1: ${{ secrets.GPG_KEY1 }}
      GPG_PASSPHRASE1: ${{ secrets.GPG_PASSPHRASE1 }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      KEY_TORRENTS: ${{ secrets.KEY_TORRENTS }}
      KNOWN_HOSTS_UPLOAD: ${{ secrets.KNOWN_HOSTS_UPLOAD }}
