name: Verify installation (pull request)
on:
  pull_request:
    types: [opened, reopened, edited, synchronize, review_requested]
    paths:
      - 'external/*.conf'
  workflow_dispatch:

jobs:

  Cancel:
    name: "Cancel currently active"
    if: ${{ github.repository_owner == 'Armbian' }}
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.13.0
        if: ${{ github.event.schedule == '' }}
        with:
          all_but_latest: true
          access_token: ${{ secrets.GITHUB_TOKEN }}

  external:
    name: "Download external"
    needs: Cancel

    if: ${{ github.repository_owner == 'Armbian' }}
    uses: armbian/scripts/.github/workflows/download-and-test-external.yml@main
    with:
      ACCESS_NAME: armbian
      BUILD_RUNNER: ubuntu-latest
      REFERENCE: ${{ github.event.pull_request.head.sha }}
    secrets:
      GPG_KEY1: ${{ secrets.GPG_KEY3 }}
      GPG_KEY2: ${{ secrets.GPG_KEY4 }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      KEY_UPLOAD: ${{ secrets.KEY_UPLOAD }}
      HOST_UPLOAD: ${{ secrets.HOST_UPLOAD }}
      HOST_UPLOAD_USER: ${{ secrets.HOST_UPLOAD_USER }}
      HOST_UPLOAD_PORT: ${{ secrets.HOST_UPLOAD_PORT }}
      KNOWN_HOSTS_ARMBIAN_UPLOAD: ${{ secrets.KNOWN_HOSTS_ARMBIAN_UPLOAD }}
