name: Smoke tests (repository update)
#
# Runs varios tests with latest nighly codebase on a real hardware
#

on:
  workflow_dispatch:
    inputs:
      gitbranch:
        description: 'Build Git Branch'
        required: false
        default: 'main'
      powermanagement:
        type: boolean
        description: "Power Management"
        default: true
  workflow_run:
    workflows: ["Repository update"]
    types:
      - completed

permissions:
  contents: read

jobs:

  Teamcheck:
    permissions:
      actions: write
      
    name: "Check ORG Team Membership"
    if: ${{ github.repository_owner == 'Armbian' }}
    runs-on: ubuntu-latest
    steps:

    - name: "Check membership"
      uses: armbian/actions/team-check@main
      with:
        ORG_MEMBERS: ${{ secrets.ORG_MEMBERS }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Smoke:
    needs: Teamcheck
    permissions:
      contents: none

    if: ${{ github.repository_owner == 'Armbian' }}
    uses: armbian/scripts/.github/workflows/smoke-tests.yml@smokey
    secrets:
      ACCESS_TOKEN_ARMBIANWORKER: ${{ secrets.ACCESS_TOKEN_ARMBIANWORKER }}
      NETBOX_TOKEN: ${{ secrets.NETBOX_TOKEN }}
      KEY_CI: ${{ secrets.KEY_CI }}      
      KEY_POWER_ON: ${{ secrets.KEY_POWER_ON }}
      KEY_POWER_OFF: ${{ secrets.KEY_POWER_OFF }}
      USER_REPOSITORY: ${{ secrets.USER_REPOSITORY }}
      HOST_REPOSITORY: ${{ secrets.HOST_REPOSITORY }}
      KNOWN_HOSTS_REPOSITORY: ${{ secrets.KNOWN_HOSTS_REPOSITORY }}
    with:
      GITBRANCH: "${{ github.event.inputs.gitbranch || 'main' }}"
      PWRMNGMT: "${{ github.event.inputs.powermanagement || 'true' }}"
